/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Carga;

/**
 *
 * @author facun
 */
public class siguiente extends javax.swing.JFrame {
        String marcaProcesador = null;
        float velocidadProcesador = 0;
        int capacidadMemoria = 0;
        int capacidadDiscoGB = 0;
        int rpm;
        String marcaPlacaVideo = null;
        int capacidadPlacaVideoMB = 0;
        float capacidadBateria = 0;
        float peso = 0 ;
        boolean perifericosBluetooth;
        String opc,tipo= null;

    /**
     * Creates new form siguiente
     */
    public siguiente() {
        initComponents();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        Contenedor = new javax.swing.JPanel();
        siguiente1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tipo1B = new javax.swing.JRadioButton();
        tipo2B = new javax.swing.JRadioButton();
        siguiente1B = new javax.swing.JButton();
        siguiente2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        marcaProcesador1B = new javax.swing.JRadioButton();
        marcaProcesador2B = new javax.swing.JRadioButton();
        siguiente2B = new javax.swing.JButton();
        siguiente3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        velocidadB = new javax.swing.JSlider();
        siguiente3B = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        valorL = new javax.swing.JLabel();
        siguiente4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        RAM1B = new javax.swing.JRadioButton();
        RAM2B = new javax.swing.JRadioButton();
        RAM3B = new javax.swing.JRadioButton();
        RAM4B = new javax.swing.JRadioButton();
        RAM5B = new javax.swing.JRadioButton();
        siguiente4B = new javax.swing.JButton();
        siguiente5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        disco1B = new javax.swing.JRadioButton();
        disco2B = new javax.swing.JRadioButton();
        disco3B = new javax.swing.JRadioButton();
        disco4B = new javax.swing.JRadioButton();
        disco5B = new javax.swing.JRadioButton();
        disco6B = new javax.swing.JRadioButton();
        disco7B = new javax.swing.JRadioButton();
        disco8B = new javax.swing.JRadioButton();
        disco9B = new javax.swing.JRadioButton();
        siguiente5B = new javax.swing.JButton();
        siguiente6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        rpmB = new javax.swing.JSlider();
        valor2L = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        siguiente7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        marca1B = new javax.swing.JRadioButton();
        marca2B = new javax.swing.JRadioButton();
        marca3B = new javax.swing.JRadioButton();
        marca4B = new javax.swing.JRadioButton();
        marca5B = new javax.swing.JRadioButton();
        marca6B = new javax.swing.JRadioButton();
        marca7B = new javax.swing.JRadioButton();
        marca8B = new javax.swing.JRadioButton();
        marca9B = new javax.swing.JRadioButton();
        marca10B = new javax.swing.JRadioButton();
        marca11B = new javax.swing.JRadioButton();
        marca12B = new javax.swing.JRadioButton();
        marca13B = new javax.swing.JRadioButton();
        marca14B = new javax.swing.JRadioButton();
        marca15B = new javax.swing.JRadioButton();
        siguiente7B = new javax.swing.JButton();
        siguiente8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        capacidadPlaca1B = new javax.swing.JRadioButton();
        capacidadPlaca2B = new javax.swing.JRadioButton();
        capacidadPlaca3B = new javax.swing.JRadioButton();
        capacidadPlaca4B = new javax.swing.JRadioButton();
        capacidadPlaca5B = new javax.swing.JRadioButton();
        capacidadPlaca6B = new javax.swing.JRadioButton();
        siguiente8B = new javax.swing.JButton();
        siguiente9N = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        capacidadBateria1B = new javax.swing.JRadioButton();
        capacidadBateria2B = new javax.swing.JRadioButton();
        capacidadBateria3B = new javax.swing.JRadioButton();
        capacidadBateria4B = new javax.swing.JRadioButton();
        siguiente9NB = new javax.swing.JButton();
        siguiente10N = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pesoB = new javax.swing.JSlider();
        pesoL = new javax.swing.JLabel();
        cargarNB = new javax.swing.JButton();
        siguiente9A = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        perifericos1B = new javax.swing.JRadioButton();
        perifericos2B = new javax.swing.JRadioButton();
        cargarAB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Contenedor.setBackground(new java.awt.Color(0, 0, 0));
        Contenedor.setLayout(new java.awt.CardLayout());

        siguiente1.setBackground(new java.awt.Color(0, 0, 0));
        siguiente1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Que tipo de computadora desea ingresar?");

        tipo1B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(tipo1B);
        tipo1B.setForeground(new java.awt.Color(255, 255, 255));
        tipo1B.setText("Notebook");

        tipo2B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(tipo2B);
        tipo2B.setForeground(new java.awt.Color(255, 255, 255));
        tipo2B.setText("All In One");

        siguiente1B.setBackground(new java.awt.Color(0, 0, 0));
        siguiente1B.setForeground(new java.awt.Color(255, 255, 255));
        siguiente1B.setText("Siguiente");
        siguiente1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente1BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente1Layout = new javax.swing.GroupLayout(siguiente1);
        siguiente1.setLayout(siguiente1Layout);
        siguiente1Layout.setHorizontalGroup(
            siguiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(siguiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipo1B)
                    .addComponent(tipo2B))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente1Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(siguiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(siguiente1B)
                    .addComponent(jLabel2))
                .addGap(84, 84, 84))
        );
        siguiente1Layout.setVerticalGroup(
            siguiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(tipo1B)
                .addGap(42, 42, 42)
                .addComponent(tipo2B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(siguiente1B)
                .addGap(47, 47, 47))
        );

        Contenedor.add(siguiente1, "card2");

        siguiente2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Indique Marca del Procesador:");

        buttonGroup2.add(marcaProcesador1B);
        marcaProcesador1B.setForeground(new java.awt.Color(255, 255, 255));
        marcaProcesador1B.setText("Intel");

        buttonGroup2.add(marcaProcesador2B);
        marcaProcesador2B.setForeground(new java.awt.Color(255, 255, 255));
        marcaProcesador2B.setText("AMD");

        siguiente2B.setBackground(new java.awt.Color(0, 0, 0));
        siguiente2B.setForeground(new java.awt.Color(255, 255, 255));
        siguiente2B.setText("Siguiente");
        siguiente2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente2BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente2Layout = new javax.swing.GroupLayout(siguiente2);
        siguiente2.setLayout(siguiente2Layout);
        siguiente2Layout.setHorizontalGroup(
            siguiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente2Layout.createSequentialGroup()
                .addGroup(siguiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siguiente2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1))
                    .addGroup(siguiente2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(siguiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marcaProcesador2B)
                            .addComponent(marcaProcesador1B))))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(siguiente2B)
                .addGap(69, 69, 69))
        );
        siguiente2Layout.setVerticalGroup(
            siguiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(marcaProcesador1B)
                .addGap(34, 34, 34)
                .addComponent(marcaProcesador2B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(siguiente2B)
                .addGap(46, 46, 46))
        );

        Contenedor.add(siguiente2, "card3");

        siguiente3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese Velocidad del Procesador:");

        velocidadB.setBackground(new java.awt.Color(255, 255, 255));
        velocidadB.setForeground(new java.awt.Color(255, 255, 255));
        velocidadB.setMaximum(4000);
        velocidadB.setMinimum(1000);
        velocidadB.setMinorTickSpacing(100);
        velocidadB.setPaintLabels(true);
        velocidadB.setPaintTicks(true);
        velocidadB.setToolTipText("");
        velocidadB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        velocidadB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                velocidadBStateChanged(evt);
            }
        });

        siguiente3B.setBackground(new java.awt.Color(0, 0, 0));
        siguiente3B.setForeground(new java.awt.Color(255, 255, 255));
        siguiente3B.setText("Siguiente");
        siguiente3B.setToolTipText("");
        siguiente3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente3BActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("1 GHz. a 4 GHz.");

        valorL.setBackground(new java.awt.Color(0, 0, 0));
        valorL.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout siguiente3Layout = new javax.swing.GroupLayout(siguiente3);
        siguiente3.setLayout(siguiente3Layout);
        siguiente3Layout.setHorizontalGroup(
            siguiente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente3Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(siguiente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente3Layout.createSequentialGroup()
                        .addComponent(siguiente3B)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente3Layout.createSequentialGroup()
                        .addComponent(velocidadB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente3Layout.createSequentialGroup()
                        .addComponent(valorL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))))
        );
        siguiente3Layout.setVerticalGroup(
            siguiente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(43, 43, 43)
                .addComponent(velocidadB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(valorL)
                .addGap(10, 10, 10)
                .addComponent(siguiente3B)
                .addGap(35, 35, 35))
        );

        Contenedor.add(siguiente3, "card4");

        siguiente4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Indique Capacidad de Memoria(RAM):");

        RAM1B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(RAM1B);
        RAM1B.setForeground(new java.awt.Color(255, 255, 255));
        RAM1B.setText("4GB.");

        RAM2B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(RAM2B);
        RAM2B.setForeground(new java.awt.Color(255, 255, 255));
        RAM2B.setText("8GB.");
        RAM2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAM2BActionPerformed(evt);
            }
        });

        RAM3B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(RAM3B);
        RAM3B.setForeground(new java.awt.Color(255, 255, 255));
        RAM3B.setText("16GB.");

        RAM4B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(RAM4B);
        RAM4B.setForeground(new java.awt.Color(255, 255, 255));
        RAM4B.setText("32GB.");

        RAM5B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(RAM5B);
        RAM5B.setForeground(new java.awt.Color(255, 255, 255));
        RAM5B.setText("64GB.");

        siguiente4B.setBackground(new java.awt.Color(0, 0, 0));
        siguiente4B.setForeground(new java.awt.Color(255, 255, 255));
        siguiente4B.setText("Siguiente");
        siguiente4B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente4BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente4Layout = new javax.swing.GroupLayout(siguiente4);
        siguiente4.setLayout(siguiente4Layout);
        siguiente4Layout.setHorizontalGroup(
            siguiente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente4Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(siguiente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente4Layout.createSequentialGroup()
                        .addComponent(siguiente4B)
                        .addGap(36, 36, 36))))
            .addGroup(siguiente4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(siguiente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RAM5B)
                    .addComponent(RAM4B)
                    .addComponent(RAM3B)
                    .addComponent(RAM2B)
                    .addComponent(RAM1B))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        siguiente4Layout.setVerticalGroup(
            siguiente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(42, 42, 42)
                .addComponent(RAM1B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RAM2B, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RAM3B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RAM4B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RAM5B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(siguiente4B)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        Contenedor.add(siguiente4, "card5");

        siguiente5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Indique Capacidad de Disco en GB:");

        buttonGroup4.add(disco1B);
        disco1B.setForeground(new java.awt.Color(255, 255, 255));
        disco1B.setText("160GB.");

        buttonGroup4.add(disco2B);
        disco2B.setForeground(new java.awt.Color(255, 255, 255));
        disco2B.setText("250GB.");

        buttonGroup4.add(disco3B);
        disco3B.setForeground(new java.awt.Color(255, 255, 255));
        disco3B.setText("320GB.");

        buttonGroup4.add(disco4B);
        disco4B.setForeground(new java.awt.Color(255, 255, 255));
        disco4B.setText("500GB.");

        buttonGroup4.add(disco5B);
        disco5B.setForeground(new java.awt.Color(255, 255, 255));
        disco5B.setText("1000GB.");

        buttonGroup4.add(disco6B);
        disco6B.setForeground(new java.awt.Color(255, 255, 255));
        disco6B.setText("1500GB.");

        buttonGroup4.add(disco7B);
        disco7B.setForeground(new java.awt.Color(255, 255, 255));
        disco7B.setText("2000GB.");

        buttonGroup4.add(disco8B);
        disco8B.setForeground(new java.awt.Color(255, 255, 255));
        disco8B.setText("2500GB.");

        buttonGroup4.add(disco9B);
        disco9B.setForeground(new java.awt.Color(255, 255, 255));
        disco9B.setText("3000GB.");

        siguiente5B.setBackground(new java.awt.Color(0, 0, 0));
        siguiente5B.setForeground(new java.awt.Color(255, 255, 255));
        siguiente5B.setText("Siguiente");
        siguiente5B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente5BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente5Layout = new javax.swing.GroupLayout(siguiente5);
        siguiente5.setLayout(siguiente5Layout);
        siguiente5Layout.setHorizontalGroup(
            siguiente5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(siguiente5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disco5B)
                    .addComponent(disco3B)
                    .addComponent(disco2B)
                    .addComponent(disco4B)
                    .addComponent(disco7B)
                    .addComponent(disco8B)
                    .addComponent(disco9B)
                    .addComponent(disco1B)
                    .addComponent(disco6B))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente5Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(siguiente5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente5Layout.createSequentialGroup()
                        .addComponent(siguiente5B)
                        .addGap(56, 56, 56))))
        );
        siguiente5Layout.setVerticalGroup(
            siguiente5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disco1B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disco2B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(disco3B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disco4B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disco5B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disco6B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disco7B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disco8B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disco9B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(siguiente5B)
                .addGap(12, 12, 12))
        );

        Contenedor.add(siguiente5, "card6");

        siguiente6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ingrese Revolucciones por Minuto del Motor del Disco:");

        rpmB.setMaximum(15000);
        rpmB.setMinimum(5000);
        rpmB.setMinorTickSpacing(100);
        rpmB.setPaintLabels(true);
        rpmB.setPaintTicks(true);
        rpmB.setValue(5400);
        rpmB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rpmBStateChanged(evt);
            }
        });

        valor2L.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente6Layout = new javax.swing.GroupLayout(siguiente6);
        siguiente6.setLayout(siguiente6Layout);
        siguiente6Layout.setHorizontalGroup(
            siguiente6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente6Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(valor2L)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente6Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(siguiente6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente6Layout.createSequentialGroup()
                        .addComponent(rpmB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente6Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(45, 45, 45))))
        );
        siguiente6Layout.setVerticalGroup(
            siguiente6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente6Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addGap(53, 53, 53)
                .addComponent(rpmB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(valor2L)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(44, 44, 44))
        );

        Contenedor.add(siguiente6, "card7");

        siguiente7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Indique Marca de Placa de Video:");

        buttonGroup5.add(marca1B);
        marca1B.setForeground(new java.awt.Color(255, 255, 255));
        marca1B.setText("AMD AMD (BBA)");

        buttonGroup5.add(marca2B);
        marca2B.setForeground(new java.awt.Color(255, 255, 255));
        marca2B.setText("AMD ASRock");

        buttonGroup5.add(marca3B);
        marca3B.setForeground(new java.awt.Color(255, 255, 255));
        marca3B.setText("AMD Gigabyte");

        buttonGroup5.add(marca4B);
        marca4B.setForeground(new java.awt.Color(255, 255, 255));
        marca4B.setText("AMD MSI");

        buttonGroup5.add(marca5B);
        marca5B.setForeground(new java.awt.Color(255, 255, 255));
        marca5B.setText("AMD PowerColor");

        buttonGroup5.add(marca6B);
        marca6B.setForeground(new java.awt.Color(255, 255, 255));
        marca6B.setText("AMD Sapphire");

        buttonGroup5.add(marca7B);
        marca7B.setForeground(new java.awt.Color(255, 255, 255));
        marca7B.setText("AMD XFX");

        buttonGroup5.add(marca8B);
        marca8B.setForeground(new java.awt.Color(255, 255, 255));
        marca8B.setText("NVIDIA Gainward");

        buttonGroup5.add(marca9B);
        marca9B.setForeground(new java.awt.Color(255, 255, 255));
        marca9B.setText("NVIDIA Gigabyte");

        buttonGroup5.add(marca10B);
        marca10B.setForeground(new java.awt.Color(255, 255, 255));
        marca10B.setText("NVIDIA INNO3D");

        buttonGroup5.add(marca11B);
        marca11B.setForeground(new java.awt.Color(255, 255, 255));
        marca11B.setText("NVIDIA Zotac");

        buttonGroup5.add(marca12B);
        marca12B.setForeground(new java.awt.Color(255, 255, 255));
        marca12B.setText("NVIDIA KFA2");

        buttonGroup5.add(marca13B);
        marca13B.setForeground(new java.awt.Color(255, 255, 255));
        marca13B.setText("NVIDIA MSI");

        buttonGroup5.add(marca14B);
        marca14B.setForeground(new java.awt.Color(255, 255, 255));
        marca14B.setText("NVIDIA Palit");

        buttonGroup5.add(marca15B);
        marca15B.setForeground(new java.awt.Color(255, 255, 255));
        marca15B.setText("NVIDIA PNY");

        siguiente7B.setBackground(new java.awt.Color(0, 0, 0));
        siguiente7B.setForeground(new java.awt.Color(255, 255, 255));
        siguiente7B.setText("Siguiente");
        siguiente7B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente7BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente7Layout = new javax.swing.GroupLayout(siguiente7);
        siguiente7.setLayout(siguiente7Layout);
        siguiente7Layout.setHorizontalGroup(
            siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente7Layout.createSequentialGroup()
                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siguiente7Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel8))
                    .addGroup(siguiente7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(marca8B))
                    .addGroup(siguiente7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marca3B)
                            .addComponent(marca1B)
                            .addComponent(marca2B)
                            .addComponent(marca4B)
                            .addComponent(marca5B)
                            .addComponent(marca6B)
                            .addComponent(marca7B))
                        .addGap(150, 150, 150)
                        .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marca15B)
                            .addComponent(marca14B)
                            .addComponent(marca13B)
                            .addComponent(marca12B)
                            .addComponent(marca10B)
                            .addComponent(marca9B)
                            .addComponent(marca11B)
                            .addComponent(siguiente7B))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        siguiente7Layout.setVerticalGroup(
            siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca1B)
                    .addComponent(marca9B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca2B)
                    .addComponent(marca10B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca3B)
                    .addComponent(marca11B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca4B)
                    .addComponent(marca12B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca5B)
                    .addComponent(marca13B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca6B)
                    .addComponent(marca14B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca7B)
                    .addComponent(marca15B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marca8B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(siguiente7B)
                .addGap(40, 40, 40))
        );

        Contenedor.add(siguiente7, "card8");

        siguiente8.setBackground(new java.awt.Color(0, 0, 0));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Indique Capacidad de la Placa de Video en MB:");

        buttonGroup6.add(capacidadPlaca1B);
        capacidadPlaca1B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadPlaca1B.setText("2048MB");

        buttonGroup6.add(capacidadPlaca2B);
        capacidadPlaca2B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadPlaca2B.setText("4096MB");

        buttonGroup6.add(capacidadPlaca3B);
        capacidadPlaca3B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadPlaca3B.setText("6144MB");

        buttonGroup6.add(capacidadPlaca4B);
        capacidadPlaca4B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadPlaca4B.setText("8192MB");

        buttonGroup6.add(capacidadPlaca5B);
        capacidadPlaca5B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadPlaca5B.setText("12288MB");

        buttonGroup6.add(capacidadPlaca6B);
        capacidadPlaca6B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadPlaca6B.setText("24576MB");

        siguiente8B.setBackground(new java.awt.Color(0, 0, 0));
        siguiente8B.setForeground(new java.awt.Color(255, 255, 255));
        siguiente8B.setText("Siguiente");
        siguiente8B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente8BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente8Layout = new javax.swing.GroupLayout(siguiente8);
        siguiente8.setLayout(siguiente8Layout);
        siguiente8Layout.setHorizontalGroup(
            siguiente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(siguiente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(capacidadPlaca1B)
                    .addComponent(capacidadPlaca2B)
                    .addComponent(capacidadPlaca3B)
                    .addComponent(capacidadPlaca4B)
                    .addGroup(siguiente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(capacidadPlaca6B)
                        .addComponent(capacidadPlaca5B)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente8Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(siguiente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente8Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente8Layout.createSequentialGroup()
                        .addComponent(siguiente8B)
                        .addGap(39, 39, 39))))
        );
        siguiente8Layout.setVerticalGroup(
            siguiente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(capacidadPlaca1B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(capacidadPlaca2B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(capacidadPlaca3B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(capacidadPlaca4B)
                .addGap(12, 12, 12)
                .addComponent(capacidadPlaca5B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(capacidadPlaca6B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(siguiente8B)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        Contenedor.add(siguiente8, "card9");

        siguiente9N.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Indique Capacidad de la Bateria:");

        capacidadBateria1B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup7.add(capacidadBateria1B);
        capacidadBateria1B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadBateria1B.setText("4400mAh");

        capacidadBateria2B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup7.add(capacidadBateria2B);
        capacidadBateria2B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadBateria2B.setText("5200mAh");

        capacidadBateria3B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup7.add(capacidadBateria3B);
        capacidadBateria3B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadBateria3B.setText("5600mAh");

        capacidadBateria4B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup7.add(capacidadBateria4B);
        capacidadBateria4B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadBateria4B.setText("5800mAh");

        siguiente9NB.setBackground(new java.awt.Color(0, 0, 0));
        siguiente9NB.setForeground(new java.awt.Color(255, 255, 255));
        siguiente9NB.setText("Siguiente");
        siguiente9NB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente9NBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente9NLayout = new javax.swing.GroupLayout(siguiente9N);
        siguiente9N.setLayout(siguiente9NLayout);
        siguiente9NLayout.setHorizontalGroup(
            siguiente9NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente9NLayout.createSequentialGroup()
                .addGroup(siguiente9NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siguiente9NLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel10))
                    .addGroup(siguiente9NLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(capacidadBateria1B))
                    .addGroup(siguiente9NLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(capacidadBateria2B))
                    .addGroup(siguiente9NLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(capacidadBateria3B))
                    .addGroup(siguiente9NLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(capacidadBateria4B)))
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente9NLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(siguiente9NB)
                .addGap(38, 38, 38))
        );
        siguiente9NLayout.setVerticalGroup(
            siguiente9NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente9NLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(capacidadBateria1B)
                .addGap(18, 18, 18)
                .addComponent(capacidadBateria2B)
                .addGap(18, 18, 18)
                .addComponent(capacidadBateria3B)
                .addGap(18, 18, 18)
                .addComponent(capacidadBateria4B)
                .addGap(18, 18, 18)
                .addComponent(siguiente9NB)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        Contenedor.add(siguiente9N, "card10");

        siguiente10N.setBackground(new java.awt.Color(0, 0, 0));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ingrese Peso en Kg.:");

        pesoB.setMaximum(3000);
        pesoB.setMinimum(600);
        pesoB.setMinorTickSpacing(100);
        pesoB.setPaintLabels(true);
        pesoB.setPaintTicks(true);
        pesoB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pesoBStateChanged(evt);
            }
        });

        pesoL.setForeground(new java.awt.Color(255, 255, 255));

        cargarNB.setBackground(new java.awt.Color(0, 0, 0));
        cargarNB.setForeground(new java.awt.Color(255, 255, 255));
        cargarNB.setText("Cargar");

        javax.swing.GroupLayout siguiente10NLayout = new javax.swing.GroupLayout(siguiente10N);
        siguiente10N.setLayout(siguiente10NLayout);
        siguiente10NLayout.setHorizontalGroup(
            siguiente10NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente10NLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(pesoL)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente10NLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(siguiente10NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente10NLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente10NLayout.createSequentialGroup()
                        .addComponent(pesoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente10NLayout.createSequentialGroup()
                        .addComponent(cargarNB)
                        .addGap(37, 37, 37))))
        );
        siguiente10NLayout.setVerticalGroup(
            siguiente10NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente10NLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel11)
                .addGap(43, 43, 43)
                .addComponent(pesoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(pesoL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(cargarNB)
                .addGap(48, 48, 48))
        );

        Contenedor.add(siguiente10N, "card11");

        siguiente9A.setBackground(new java.awt.Color(0, 0, 0));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Indique si su Perifericos Soportan Bluetooth:");

        buttonGroup8.add(perifericos1B);
        perifericos1B.setForeground(new java.awt.Color(255, 255, 255));
        perifericos1B.setText("SI");

        buttonGroup8.add(perifericos2B);
        perifericos2B.setForeground(new java.awt.Color(255, 255, 255));
        perifericos2B.setText("NO");

        cargarAB.setBackground(new java.awt.Color(0, 0, 0));
        cargarAB.setForeground(new java.awt.Color(255, 255, 255));
        cargarAB.setText("Cargar");

        javax.swing.GroupLayout siguiente9ALayout = new javax.swing.GroupLayout(siguiente9A);
        siguiente9A.setLayout(siguiente9ALayout);
        siguiente9ALayout.setHorizontalGroup(
            siguiente9ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente9ALayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cargarAB)
                .addGap(33, 33, 33))
            .addGroup(siguiente9ALayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel12)
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(siguiente9ALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(perifericos1B)
                .addGap(87, 87, 87)
                .addComponent(perifericos2B)
                .addGap(123, 123, 123))
        );
        siguiente9ALayout.setVerticalGroup(
            siguiente9ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente9ALayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel12)
                .addGap(52, 52, 52)
                .addGroup(siguiente9ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perifericos1B)
                    .addComponent(perifericos2B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(cargarAB)
                .addGap(39, 39, 39))
        );

        Contenedor.add(siguiente9A, "card12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguiente1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente1BActionPerformed
        // TODO add your handling code here:
        if(tipo1B.isSelected()){
            tipo = tipo1B.getText();
        }
        if(tipo2B.isSelected()){
            tipo = tipo2B.getText();
        }
        if(tipo!=null){
            Contenedor.removeAll();
            Contenedor.add(siguiente2);
            Contenedor.repaint();
            Contenedor.revalidate();
        }
    }//GEN-LAST:event_siguiente1BActionPerformed

    private void siguiente2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente2BActionPerformed
        // TODO add your handling code here:
        if(marcaProcesador1B.isSelected()){
            marcaProcesador = marcaProcesador1B.getText();
        }
        if(marcaProcesador2B.isSelected()){
            marcaProcesador = marcaProcesador2B.getText();
        }
        if(marcaProcesador!=null){
            Contenedor.removeAll();
            Contenedor.add(siguiente3);
            Contenedor.repaint();
            Contenedor.revalidate();
        }
    }//GEN-LAST:event_siguiente2BActionPerformed

    private void velocidadBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_velocidadBStateChanged
        // TODO add your handling code here:
        valorL.setText(((float)velocidadB.getValue()/1000)+"GHz.");
    }//GEN-LAST:event_velocidadBStateChanged

    private void siguiente3BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente3BActionPerformed
        // TODO add your handling code here:
        velocidadProcesador = (float)velocidadB.getValue();
        if(velocidadProcesador!=0){
            Contenedor.removeAll();
            Contenedor.add(siguiente4);
            Contenedor.repaint();
            Contenedor.revalidate();
        }
    }//GEN-LAST:event_siguiente3BActionPerformed

    private void RAM2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAM2BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RAM2BActionPerformed

    private void siguiente4BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente4BActionPerformed
        // TODO add your handling code here:
        if(RAM1B.isSelected()){
            capacidadMemoria = 4;
        }
        if(RAM2B.isSelected()){
            capacidadMemoria = 8;
        }
        if(RAM3B.isSelected()){
            capacidadMemoria = 16;
        }
        if(RAM4B.isSelected()){
            capacidadMemoria = 32;
        }
        if(RAM5B.isSelected()){
            capacidadMemoria = 64;
        }
        if(capacidadMemoria != 0){
            Contenedor.removeAll();
            Contenedor.add(siguiente5);
            Contenedor.repaint();
            Contenedor.revalidate();
        }
    }//GEN-LAST:event_siguiente4BActionPerformed

    private void siguiente5BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente5BActionPerformed
        // TODO add your handling code here:
        if(disco1B.isSelected()){
            capacidadDiscoGB = 160;
        }
        if(disco2B.isSelected()){
            capacidadDiscoGB = 250;
        }
        if(disco3B.isSelected()){
            capacidadDiscoGB = 320;
        }
        if(disco4B.isSelected()){
            capacidadDiscoGB = 500;
        }
        if(disco5B.isSelected()){
            capacidadDiscoGB = 1000;
        }
        if(disco6B.isSelected()){
            capacidadDiscoGB = 1500;
        }
        if(disco7B.isSelected()){
            capacidadDiscoGB = 2000;
        }
        if(disco8B.isSelected()){
            capacidadDiscoGB = 2500;
        }
        if(disco9B.isSelected()){
            capacidadDiscoGB = 3000;
        }
        
        if(capacidadDiscoGB!=0){
            Contenedor.removeAll();
            Contenedor.add(siguiente6);
            Contenedor.repaint();
            Contenedor.revalidate();
        }
    }//GEN-LAST:event_siguiente5BActionPerformed

    private void rpmBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rpmBStateChanged
        // TODO add your handling code here:
        valor2L.setText(rpmB.getValue()+"rpm.");
    }//GEN-LAST:event_rpmBStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        rpm = rpmB.getValue();
        Contenedor.removeAll();
        Contenedor.add(siguiente7);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void siguiente7BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente7BActionPerformed
        // TODO add your handling code here:
        if(marca1B.isSelected()){
            marcaPlacaVideo = marca1B.getText();
        }
        if(marca2B.isSelected()){
            marcaPlacaVideo = marca2B.getText();
        }
        if(marca3B.isSelected()){
            marcaPlacaVideo = marca3B.getText();
        }
        if(marca4B.isSelected()){
            marcaPlacaVideo = marca4B.getText();
        }
        if(marca5B.isSelected()){
            marcaPlacaVideo = marca5B.getText();
        }
        if(marca6B.isSelected()){
            marcaPlacaVideo = marca6B.getText();
        }
        if(marca7B.isSelected()){
            marcaPlacaVideo = marca7B.getText();
        }
        if(marca8B.isSelected()){
            marcaPlacaVideo = marca8B.getText();
        }
        if(marca9B.isSelected()){
            marcaPlacaVideo = marca9B.getText();
        }
        if(marca10B.isSelected()){
            marcaPlacaVideo = marca10B.getText();
        }
        if(marca11B.isSelected()){
            marcaPlacaVideo = marca11B.getText();
        }
        if(marca12B.isSelected()){
            marcaPlacaVideo = marca12B.getText();
        }
        if(marca13B.isSelected()){
            marcaPlacaVideo = marca13B.getText();
        }
        if(marca14B.isSelected()){
            marcaPlacaVideo = marca14B.getText();
        }
        if(marca15B.isSelected()){
            marcaPlacaVideo = marca15B.getText();
        }
        if(marcaPlacaVideo!=null){
            Contenedor.removeAll();
            Contenedor.add(siguiente8);
            Contenedor.repaint();
            Contenedor.revalidate();
        }
    }//GEN-LAST:event_siguiente7BActionPerformed

    private void siguiente8BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente8BActionPerformed
        // TODO add your handling code here:
        if(capacidadPlaca1B.isSelected()){
            capacidadPlacaVideoMB = 2048;
        }
        if(capacidadPlaca2B.isSelected()){
            capacidadPlacaVideoMB = 4096;
        }
        if(capacidadPlaca3B.isSelected()){
            capacidadPlacaVideoMB = 6144;
        }
        if(capacidadPlaca4B.isSelected()){
            capacidadPlacaVideoMB = 8192;
        }
        if(capacidadPlaca5B.isSelected()){
            capacidadPlacaVideoMB = 12288;
        }
        if(capacidadPlaca6B.isSelected()){
            capacidadPlacaVideoMB = 24576;
        }
        if(capacidadPlacaVideoMB != 0){
            if(tipo.equals("Notebook")){
                Contenedor.removeAll();
                Contenedor.add(siguiente9N);
                Contenedor.repaint();
                Contenedor.revalidate();
            }else{
                Contenedor.removeAll();
                Contenedor.add(siguiente9A);
                Contenedor.repaint();
                Contenedor.revalidate();
            }
        }
        
    }//GEN-LAST:event_siguiente8BActionPerformed

    private void siguiente9NBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente9NBActionPerformed
        // TODO add your handling code here:
        if(capacidadBateria1B.isSelected()){
            capacidadBateria = 4400;
        }
        if(capacidadBateria2B.isSelected()){
            capacidadBateria = 5200;
        }
        if(capacidadBateria3B.isSelected()){
            capacidadBateria = 5600;
        }
        if(capacidadBateria4B.isSelected()){
            capacidadBateria = 5800;
        }
        if(capacidadBateria!=0){
            Contenedor.removeAll();
            Contenedor.add(siguiente10N);
            Contenedor.repaint();
            Contenedor.revalidate();
        }
    }//GEN-LAST:event_siguiente9NBActionPerformed

    private void pesoBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pesoBStateChanged
        // TODO add your handling code here:
        pesoL.setText(((float)pesoB.getValue()/1000)+"Kg.");
    }//GEN-LAST:event_pesoBStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(siguiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(siguiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(siguiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(siguiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new siguiente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JRadioButton RAM1B;
    private javax.swing.JRadioButton RAM2B;
    private javax.swing.JRadioButton RAM3B;
    private javax.swing.JRadioButton RAM4B;
    private javax.swing.JRadioButton RAM5B;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JRadioButton capacidadBateria1B;
    private javax.swing.JRadioButton capacidadBateria2B;
    private javax.swing.JRadioButton capacidadBateria3B;
    private javax.swing.JRadioButton capacidadBateria4B;
    private javax.swing.JRadioButton capacidadPlaca1B;
    private javax.swing.JRadioButton capacidadPlaca2B;
    private javax.swing.JRadioButton capacidadPlaca3B;
    private javax.swing.JRadioButton capacidadPlaca4B;
    private javax.swing.JRadioButton capacidadPlaca5B;
    private javax.swing.JRadioButton capacidadPlaca6B;
    private javax.swing.JButton cargarAB;
    private javax.swing.JButton cargarNB;
    private javax.swing.JRadioButton disco1B;
    private javax.swing.JRadioButton disco2B;
    private javax.swing.JRadioButton disco3B;
    private javax.swing.JRadioButton disco4B;
    private javax.swing.JRadioButton disco5B;
    private javax.swing.JRadioButton disco6B;
    private javax.swing.JRadioButton disco7B;
    private javax.swing.JRadioButton disco8B;
    private javax.swing.JRadioButton disco9B;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton marca10B;
    private javax.swing.JRadioButton marca11B;
    private javax.swing.JRadioButton marca12B;
    private javax.swing.JRadioButton marca13B;
    private javax.swing.JRadioButton marca14B;
    private javax.swing.JRadioButton marca15B;
    private javax.swing.JRadioButton marca1B;
    private javax.swing.JRadioButton marca2B;
    private javax.swing.JRadioButton marca3B;
    private javax.swing.JRadioButton marca4B;
    private javax.swing.JRadioButton marca5B;
    private javax.swing.JRadioButton marca6B;
    private javax.swing.JRadioButton marca7B;
    private javax.swing.JRadioButton marca8B;
    private javax.swing.JRadioButton marca9B;
    private javax.swing.JRadioButton marcaProcesador1B;
    private javax.swing.JRadioButton marcaProcesador2B;
    private javax.swing.JRadioButton perifericos1B;
    private javax.swing.JRadioButton perifericos2B;
    private javax.swing.JSlider pesoB;
    private javax.swing.JLabel pesoL;
    private javax.swing.JSlider rpmB;
    private javax.swing.JPanel siguiente1;
    private javax.swing.JPanel siguiente10N;
    private javax.swing.JButton siguiente1B;
    private javax.swing.JPanel siguiente2;
    private javax.swing.JButton siguiente2B;
    private javax.swing.JPanel siguiente3;
    private javax.swing.JButton siguiente3B;
    private javax.swing.JPanel siguiente4;
    private javax.swing.JButton siguiente4B;
    private javax.swing.JPanel siguiente5;
    private javax.swing.JButton siguiente5B;
    private javax.swing.JPanel siguiente6;
    private javax.swing.JPanel siguiente7;
    private javax.swing.JButton siguiente7B;
    private javax.swing.JPanel siguiente8;
    private javax.swing.JButton siguiente8B;
    private javax.swing.JPanel siguiente9A;
    private javax.swing.JPanel siguiente9N;
    private javax.swing.JButton siguiente9NB;
    private javax.swing.JRadioButton tipo1B;
    private javax.swing.JRadioButton tipo2B;
    private javax.swing.JLabel valor2L;
    private javax.swing.JLabel valorL;
    private javax.swing.JSlider velocidadB;
    // End of variables declaration//GEN-END:variables
}
