/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Modelo.All_In_One;
import Modelo.Computadora;
import Modelo.NegocioDeComputadora;
import Modelo.Notebook;
import Paneles.Inicio;
import java.awt.PopupMenu;
import java.util.ListIterator;

/**
 *
 * @author facun
 */
public class Principal extends javax.swing.JFrame {
    NegocioDeComputadora inventario = new NegocioDeComputadora();
    ListIterator<Computadora> it /*= inventario.getNegocio().listIterator()*/;
        String marcaProcesador = null;
        float velocidadProcesador = 0;
        int capacidadMemoria = 0;
        int capacidadDiscoGB = 0;
        int rpm;
        String marcaPlacaVideo = null;
        int capacidadPlacaVideoMB = 0;
        int capacidadBateria = 0;
        float peso = 0 ;
        boolean perifericosBluetooth = false;
        String tipo= null;
       


    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cargarB = new javax.swing.JButton();
        mostrarB = new javax.swing.JButton();
        inicioB = new javax.swing.JButton();
        Contenedor = new javax.swing.JPanel();
        Inicio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Carga = new javax.swing.JPanel();
        siguiente1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tipo1B = new javax.swing.JRadioButton();
        tipo2B = new javax.swing.JRadioButton();
        siguiente1B = new javax.swing.JButton();
        siguiente2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        marcaProcesador1B = new javax.swing.JRadioButton();
        marcaProcesador2B = new javax.swing.JRadioButton();
        siguiente2B = new javax.swing.JButton();
        anterior2B = new javax.swing.JButton();
        siguiente3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        velocidadB = new javax.swing.JSlider();
        siguiente3B = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        valorL = new javax.swing.JLabel();
        anterior3B = new javax.swing.JButton();
        siguiente4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        RAM1B = new javax.swing.JRadioButton();
        RAM2B = new javax.swing.JRadioButton();
        RAM3B = new javax.swing.JRadioButton();
        RAM4B = new javax.swing.JRadioButton();
        RAM5B = new javax.swing.JRadioButton();
        siguiente4B = new javax.swing.JButton();
        anterior4B = new javax.swing.JButton();
        siguiente5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        disco1B = new javax.swing.JRadioButton();
        disco2B = new javax.swing.JRadioButton();
        disco3B = new javax.swing.JRadioButton();
        disco4B = new javax.swing.JRadioButton();
        disco5B = new javax.swing.JRadioButton();
        disco6B = new javax.swing.JRadioButton();
        disco7B = new javax.swing.JRadioButton();
        disco8B = new javax.swing.JRadioButton();
        disco9B = new javax.swing.JRadioButton();
        siguiente5B = new javax.swing.JButton();
        anterior5B = new javax.swing.JButton();
        siguiente6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        rpmB = new javax.swing.JSlider();
        valor2L = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        anterior6B = new javax.swing.JButton();
        siguiente7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        marca1B = new javax.swing.JRadioButton();
        marca2B = new javax.swing.JRadioButton();
        marca3B = new javax.swing.JRadioButton();
        marca4B = new javax.swing.JRadioButton();
        marca5B = new javax.swing.JRadioButton();
        marca6B = new javax.swing.JRadioButton();
        marca7B = new javax.swing.JRadioButton();
        marca8B = new javax.swing.JRadioButton();
        marca9B = new javax.swing.JRadioButton();
        marca10B = new javax.swing.JRadioButton();
        marca11B = new javax.swing.JRadioButton();
        marca12B = new javax.swing.JRadioButton();
        marca13B = new javax.swing.JRadioButton();
        marca14B = new javax.swing.JRadioButton();
        marca15B = new javax.swing.JRadioButton();
        siguiente7B = new javax.swing.JButton();
        anterior7B = new javax.swing.JButton();
        siguiente8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        capacidadPlaca1B = new javax.swing.JRadioButton();
        capacidadPlaca2B = new javax.swing.JRadioButton();
        capacidadPlaca3B = new javax.swing.JRadioButton();
        capacidadPlaca4B = new javax.swing.JRadioButton();
        capacidadPlaca5B = new javax.swing.JRadioButton();
        capacidadPlaca6B = new javax.swing.JRadioButton();
        siguiente8B = new javax.swing.JButton();
        anterior8B = new javax.swing.JButton();
        siguiente9N = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        capacidadBateria1B = new javax.swing.JRadioButton();
        capacidadBateria2B = new javax.swing.JRadioButton();
        capacidadBateria3B = new javax.swing.JRadioButton();
        capacidadBateria4B = new javax.swing.JRadioButton();
        siguiente9NB = new javax.swing.JButton();
        anterior9NB = new javax.swing.JButton();
        siguiente10N = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pesoB = new javax.swing.JSlider();
        pesoL = new javax.swing.JLabel();
        cargarNB = new javax.swing.JButton();
        anterior10NB = new javax.swing.JButton();
        siguiente9A = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        perifericos1B = new javax.swing.JRadioButton();
        perifericos2B = new javax.swing.JRadioButton();
        cargarAB = new javax.swing.JButton();
        anterior9AB = new javax.swing.JButton();
        Muestra = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        muestraText = new javax.swing.JTextArea();
        siguienteM = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        anteriorM = new javax.swing.JButton();
        terminarM = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        cargarB.setBackground(new java.awt.Color(0, 0, 0));
        cargarB.setForeground(new java.awt.Color(255, 255, 255));
        cargarB.setText("CARGAR");
        cargarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarBActionPerformed(evt);
            }
        });

        mostrarB.setBackground(new java.awt.Color(0, 0, 0));
        mostrarB.setForeground(new java.awt.Color(255, 255, 255));
        mostrarB.setText("MOSTRAR");
        mostrarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarBActionPerformed(evt);
            }
        });

        inicioB.setBackground(new java.awt.Color(0, 0, 0));
        inicioB.setForeground(new java.awt.Color(255, 255, 255));
        inicioB.setText("INICIO");
        inicioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(cargarB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(mostrarB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(inicioB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargarB)
                    .addComponent(inicioB)
                    .addComponent(mostrarB))
                .addGap(43, 43, 43))
        );

        Contenedor.setBackground(new java.awt.Color(102, 255, 0));
        Contenedor.setLayout(new java.awt.CardLayout());

        Inicio.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("COMPUTADORAS");

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel2)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        Contenedor.add(Inicio, "card3");

        Carga.setLayout(new java.awt.CardLayout());

        siguiente1.setBackground(new java.awt.Color(0, 0, 0));
        siguiente1.setForeground(new java.awt.Color(255, 255, 255));
        siguiente1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        siguiente1.setPreferredSize(new java.awt.Dimension(400, 351));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Que tipo de computadora desea ingresar?");

        tipo1B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(tipo1B);
        tipo1B.setForeground(new java.awt.Color(255, 255, 255));
        tipo1B.setText("Notebook");

        tipo2B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(tipo2B);
        tipo2B.setForeground(new java.awt.Color(255, 255, 255));
        tipo2B.setText("All In One");

        siguiente1B.setBackground(new java.awt.Color(0, 0, 0));
        siguiente1B.setForeground(new java.awt.Color(255, 255, 255));
        siguiente1B.setText("Siguiente");
        siguiente1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente1BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente1Layout = new javax.swing.GroupLayout(siguiente1);
        siguiente1.setLayout(siguiente1Layout);
        siguiente1Layout.setHorizontalGroup(
            siguiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(siguiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente1Layout.createSequentialGroup()
                        .addGroup(siguiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(siguiente1Layout.createSequentialGroup()
                                .addComponent(tipo1B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tipo2B))
                            .addComponent(jLabel3))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente1Layout.createSequentialGroup()
                        .addComponent(siguiente1B)
                        .addGap(37, 37, 37))))
        );
        siguiente1Layout.setVerticalGroup(
            siguiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel3)
                .addGap(58, 58, 58)
                .addGroup(siguiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo2B)
                    .addComponent(tipo1B))
                .addGap(59, 59, 59)
                .addComponent(siguiente1B)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        Carga.add(siguiente1, "card2");

        siguiente2.setBackground(new java.awt.Color(0, 0, 0));
        siguiente2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Indique Marca del Procesador:");

        buttonGroup2.add(marcaProcesador1B);
        marcaProcesador1B.setForeground(new java.awt.Color(255, 255, 255));
        marcaProcesador1B.setText("Intel");

        buttonGroup2.add(marcaProcesador2B);
        marcaProcesador2B.setForeground(new java.awt.Color(255, 255, 255));
        marcaProcesador2B.setText("AMD");

        siguiente2B.setBackground(new java.awt.Color(0, 0, 0));
        siguiente2B.setForeground(new java.awt.Color(255, 255, 255));
        siguiente2B.setText("Siguiente");
        siguiente2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente2BActionPerformed(evt);
            }
        });

        anterior2B.setBackground(new java.awt.Color(0, 0, 0));
        anterior2B.setForeground(new java.awt.Color(255, 255, 255));
        anterior2B.setText("Anterior");
        anterior2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anterior2BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente2Layout = new javax.swing.GroupLayout(siguiente2);
        siguiente2.setLayout(siguiente2Layout);
        siguiente2Layout.setHorizontalGroup(
            siguiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(anterior2B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siguiente2B)
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente2Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(siguiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(siguiente2Layout.createSequentialGroup()
                        .addComponent(marcaProcesador1B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(marcaProcesador2B))
                    .addComponent(jLabel1))
                .addGap(114, 114, 114))
        );
        siguiente2Layout.setVerticalGroup(
            siguiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(siguiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaProcesador2B)
                    .addComponent(marcaProcesador1B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(siguiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguiente2B)
                    .addComponent(anterior2B))
                .addGap(45, 45, 45))
        );

        Carga.add(siguiente2, "card3");

        siguiente3.setBackground(new java.awt.Color(0, 0, 0));
        siguiente3.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrese Velocidad del Procesador:");

        velocidadB.setBackground(new java.awt.Color(255, 255, 255));
        velocidadB.setForeground(new java.awt.Color(255, 255, 255));
        velocidadB.setMaximum(6000);
        velocidadB.setMinimum(1000);
        velocidadB.setMinorTickSpacing(100);
        velocidadB.setPaintLabels(true);
        velocidadB.setPaintTicks(true);
        velocidadB.setToolTipText("");
        velocidadB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        velocidadB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                velocidadBStateChanged(evt);
            }
        });

        siguiente3B.setBackground(new java.awt.Color(0, 0, 0));
        siguiente3B.setForeground(new java.awt.Color(255, 255, 255));
        siguiente3B.setText("Siguiente");
        siguiente3B.setToolTipText("");
        siguiente3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente3BActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("1 GHz. a 6 GHz.");

        valorL.setBackground(new java.awt.Color(0, 0, 0));
        valorL.setForeground(new java.awt.Color(255, 255, 255));

        anterior3B.setBackground(new java.awt.Color(0, 0, 0));
        anterior3B.setForeground(new java.awt.Color(255, 255, 255));
        anterior3B.setText("Anterior");
        anterior3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anterior3BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente3Layout = new javax.swing.GroupLayout(siguiente3);
        siguiente3.setLayout(siguiente3Layout);
        siguiente3Layout.setHorizontalGroup(
            siguiente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente3Layout.createSequentialGroup()
                .addGroup(siguiente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siguiente3Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel7))
                    .addGroup(siguiente3Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(valorL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente3Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(siguiente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente3Layout.createSequentialGroup()
                        .addComponent(velocidadB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(anterior3B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siguiente3B)
                .addGap(38, 38, 38))
        );
        siguiente3Layout.setVerticalGroup(
            siguiente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(velocidadB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(valorL, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(siguiente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguiente3B)
                    .addComponent(anterior3B))
                .addGap(37, 37, 37))
        );

        Carga.add(siguiente3, "card4");

        siguiente4.setBackground(new java.awt.Color(0, 0, 0));
        siguiente4.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Indique Capacidad de Memoria(RAM):");

        RAM1B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(RAM1B);
        RAM1B.setForeground(new java.awt.Color(255, 255, 255));
        RAM1B.setText("4GB.");

        RAM2B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(RAM2B);
        RAM2B.setForeground(new java.awt.Color(255, 255, 255));
        RAM2B.setText("8GB.");
        RAM2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAM2BActionPerformed(evt);
            }
        });

        RAM3B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(RAM3B);
        RAM3B.setForeground(new java.awt.Color(255, 255, 255));
        RAM3B.setText("16GB.");

        RAM4B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(RAM4B);
        RAM4B.setForeground(new java.awt.Color(255, 255, 255));
        RAM4B.setText("32GB.");

        RAM5B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(RAM5B);
        RAM5B.setForeground(new java.awt.Color(255, 255, 255));
        RAM5B.setText("64GB.");

        siguiente4B.setBackground(new java.awt.Color(0, 0, 0));
        siguiente4B.setForeground(new java.awt.Color(255, 255, 255));
        siguiente4B.setText("Siguiente");
        siguiente4B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente4BActionPerformed(evt);
            }
        });

        anterior4B.setBackground(new java.awt.Color(0, 0, 0));
        anterior4B.setForeground(new java.awt.Color(255, 255, 255));
        anterior4B.setText("Anterior");
        anterior4B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anterior4BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente4Layout = new javax.swing.GroupLayout(siguiente4);
        siguiente4.setLayout(siguiente4Layout);
        siguiente4Layout.setHorizontalGroup(
            siguiente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente4Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(siguiente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RAM3B)
                    .addComponent(jLabel5)
                    .addGroup(siguiente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(siguiente4Layout.createSequentialGroup()
                            .addComponent(RAM2B)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RAM5B))
                        .addGroup(siguiente4Layout.createSequentialGroup()
                            .addComponent(RAM1B)
                            .addGap(93, 93, 93)
                            .addComponent(RAM4B))))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(anterior4B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siguiente4B)
                .addGap(38, 38, 38))
        );
        siguiente4Layout.setVerticalGroup(
            siguiente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente4Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(siguiente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RAM1B)
                    .addComponent(RAM4B))
                .addGap(18, 18, 18)
                .addGroup(siguiente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RAM2B, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RAM5B))
                .addGap(18, 18, 18)
                .addComponent(RAM3B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(siguiente4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguiente4B)
                    .addComponent(anterior4B))
                .addGap(38, 38, 38))
        );

        Carga.add(siguiente4, "card5");

        siguiente5.setBackground(new java.awt.Color(0, 0, 0));
        siguiente5.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        siguiente5.setPreferredSize(new java.awt.Dimension(400, 351));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Indique Capacidad de Disco en GB:");

        buttonGroup4.add(disco1B);
        disco1B.setForeground(new java.awt.Color(255, 255, 255));
        disco1B.setText("160GB.");

        buttonGroup4.add(disco2B);
        disco2B.setForeground(new java.awt.Color(255, 255, 255));
        disco2B.setText("250GB.");

        buttonGroup4.add(disco3B);
        disco3B.setForeground(new java.awt.Color(255, 255, 255));
        disco3B.setText("320GB.");

        buttonGroup4.add(disco4B);
        disco4B.setForeground(new java.awt.Color(255, 255, 255));
        disco4B.setText("500GB.");

        buttonGroup4.add(disco5B);
        disco5B.setForeground(new java.awt.Color(255, 255, 255));
        disco5B.setText("1000GB.");

        buttonGroup4.add(disco6B);
        disco6B.setForeground(new java.awt.Color(255, 255, 255));
        disco6B.setText("1500GB.");

        buttonGroup4.add(disco7B);
        disco7B.setForeground(new java.awt.Color(255, 255, 255));
        disco7B.setText("2000GB.");

        buttonGroup4.add(disco8B);
        disco8B.setForeground(new java.awt.Color(255, 255, 255));
        disco8B.setText("2500GB.");

        buttonGroup4.add(disco9B);
        disco9B.setForeground(new java.awt.Color(255, 255, 255));
        disco9B.setText("3000GB.");

        siguiente5B.setBackground(new java.awt.Color(0, 0, 0));
        siguiente5B.setForeground(new java.awt.Color(255, 255, 255));
        siguiente5B.setText("Siguiente");
        siguiente5B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente5BActionPerformed(evt);
            }
        });

        anterior5B.setBackground(new java.awt.Color(0, 0, 0));
        anterior5B.setForeground(new java.awt.Color(255, 255, 255));
        anterior5B.setText("Anterior");
        anterior5B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anterior5BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente5Layout = new javax.swing.GroupLayout(siguiente5);
        siguiente5.setLayout(siguiente5Layout);
        siguiente5Layout.setHorizontalGroup(
            siguiente5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente5Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(107, 107, 107))
            .addGroup(siguiente5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(siguiente5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, siguiente5Layout.createSequentialGroup()
                        .addComponent(disco5B)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(siguiente5Layout.createSequentialGroup()
                        .addGroup(siguiente5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(siguiente5Layout.createSequentialGroup()
                                .addComponent(disco4B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(disco9B))
                            .addGroup(siguiente5Layout.createSequentialGroup()
                                .addComponent(disco3B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(disco8B))
                            .addGroup(siguiente5Layout.createSequentialGroup()
                                .addComponent(disco2B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(disco7B))
                            .addGroup(siguiente5Layout.createSequentialGroup()
                                .addComponent(disco1B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(disco6B)))
                        .addGap(56, 56, 56))
                    .addGroup(siguiente5Layout.createSequentialGroup()
                        .addComponent(anterior5B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(siguiente5B)
                        .addGap(42, 42, 42))))
        );
        siguiente5Layout.setVerticalGroup(
            siguiente5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(siguiente5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disco1B)
                    .addComponent(disco6B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siguiente5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disco2B)
                    .addComponent(disco7B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siguiente5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disco3B)
                    .addComponent(disco8B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siguiente5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disco4B)
                    .addComponent(disco9B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disco5B)
                .addGap(66, 66, 66)
                .addGroup(siguiente5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anterior5B)
                    .addComponent(siguiente5B))
                .addGap(60, 60, 60))
        );

        Carga.add(siguiente5, "card6");

        siguiente6.setBackground(new java.awt.Color(0, 0, 0));
        siguiente6.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ingrese Revolucciones por Minuto del Motor del Disco:");

        rpmB.setMaximum(15000);
        rpmB.setMinimum(5000);
        rpmB.setMinorTickSpacing(100);
        rpmB.setPaintLabels(true);
        rpmB.setPaintTicks(true);
        rpmB.setValue(5400);
        rpmB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rpmBStateChanged(evt);
            }
        });

        valor2L.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        anterior6B.setBackground(new java.awt.Color(0, 0, 0));
        anterior6B.setForeground(new java.awt.Color(255, 255, 255));
        anterior6B.setText("Anterior");
        anterior6B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anterior6BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente6Layout = new javax.swing.GroupLayout(siguiente6);
        siguiente6.setLayout(siguiente6Layout);
        siguiente6Layout.setHorizontalGroup(
            siguiente6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(siguiente6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente6Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente6Layout.createSequentialGroup()
                        .addComponent(rpmB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
            .addGroup(siguiente6Layout.createSequentialGroup()
                .addGroup(siguiente6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siguiente6Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(valor2L, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siguiente6Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(siguiente6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anterior6B)
                            .addComponent(jLabel8))))
                .addGap(0, 63, Short.MAX_VALUE))
        );
        siguiente6Layout.setVerticalGroup(
            siguiente6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente6Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel8)
                .addGap(35, 35, 35)
                .addComponent(rpmB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(valor2L, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(siguiente6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(anterior6B))
                .addGap(44, 44, 44))
        );

        Carga.add(siguiente6, "card7");

        siguiente7.setBackground(new java.awt.Color(0, 0, 0));
        siguiente7.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Indique Marca de Placa de Video:");

        buttonGroup5.add(marca1B);
        marca1B.setForeground(new java.awt.Color(255, 255, 255));
        marca1B.setText("AMD AMD (BBA)");

        buttonGroup5.add(marca2B);
        marca2B.setForeground(new java.awt.Color(255, 255, 255));
        marca2B.setText("AMD ASRock");

        buttonGroup5.add(marca3B);
        marca3B.setForeground(new java.awt.Color(255, 255, 255));
        marca3B.setText("AMD Gigabyte");

        buttonGroup5.add(marca4B);
        marca4B.setForeground(new java.awt.Color(255, 255, 255));
        marca4B.setText("AMD MSI");

        buttonGroup5.add(marca5B);
        marca5B.setForeground(new java.awt.Color(255, 255, 255));
        marca5B.setText("AMD PowerColor");

        buttonGroup5.add(marca6B);
        marca6B.setForeground(new java.awt.Color(255, 255, 255));
        marca6B.setText("AMD Sapphire");

        buttonGroup5.add(marca7B);
        marca7B.setForeground(new java.awt.Color(255, 255, 255));
        marca7B.setText("AMD XFX");

        buttonGroup5.add(marca8B);
        marca8B.setForeground(new java.awt.Color(255, 255, 255));
        marca8B.setText("NVIDIA Gainward");

        buttonGroup5.add(marca9B);
        marca9B.setForeground(new java.awt.Color(255, 255, 255));
        marca9B.setText("NVIDIA Gigabyte");

        buttonGroup5.add(marca10B);
        marca10B.setForeground(new java.awt.Color(255, 255, 255));
        marca10B.setText("NVIDIA INNO3D");

        buttonGroup5.add(marca11B);
        marca11B.setForeground(new java.awt.Color(255, 255, 255));
        marca11B.setText("NVIDIA Zotac");

        buttonGroup5.add(marca12B);
        marca12B.setForeground(new java.awt.Color(255, 255, 255));
        marca12B.setText("NVIDIA KFA2");

        buttonGroup5.add(marca13B);
        marca13B.setForeground(new java.awt.Color(255, 255, 255));
        marca13B.setText("NVIDIA MSI");

        buttonGroup5.add(marca14B);
        marca14B.setForeground(new java.awt.Color(255, 255, 255));
        marca14B.setText("NVIDIA Palit");

        buttonGroup5.add(marca15B);
        marca15B.setForeground(new java.awt.Color(255, 255, 255));
        marca15B.setText("NVIDIA PNY");

        siguiente7B.setBackground(new java.awt.Color(0, 0, 0));
        siguiente7B.setForeground(new java.awt.Color(255, 255, 255));
        siguiente7B.setText("Siguiente");
        siguiente7B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente7BActionPerformed(evt);
            }
        });

        anterior7B.setBackground(new java.awt.Color(0, 0, 0));
        anterior7B.setForeground(new java.awt.Color(255, 255, 255));
        anterior7B.setText("Anterior");
        anterior7B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anterior7BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente7Layout = new javax.swing.GroupLayout(siguiente7);
        siguiente7.setLayout(siguiente7Layout);
        siguiente7Layout.setHorizontalGroup(
            siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente7Layout.createSequentialGroup()
                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siguiente7Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel9))
                    .addGroup(siguiente7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(marca8B))
                    .addGroup(siguiente7Layout.createSequentialGroup()
                        .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(siguiente7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(marca3B)
                                    .addComponent(marca1B)
                                    .addComponent(marca2B)
                                    .addComponent(marca4B)
                                    .addComponent(marca5B)
                                    .addComponent(marca6B)
                                    .addComponent(marca7B))
                                .addGap(150, 150, 150))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente7Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(anterior7B)
                                .addGap(151, 151, 151)))
                        .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marca15B)
                            .addComponent(marca14B)
                            .addComponent(marca13B)
                            .addComponent(marca12B)
                            .addComponent(marca10B)
                            .addComponent(marca9B)
                            .addComponent(marca11B)
                            .addComponent(siguiente7B))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        siguiente7Layout.setVerticalGroup(
            siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca1B)
                    .addComponent(marca9B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca2B)
                    .addComponent(marca10B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca3B)
                    .addComponent(marca11B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca4B)
                    .addComponent(marca12B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca5B)
                    .addComponent(marca13B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca6B)
                    .addComponent(marca14B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca7B)
                    .addComponent(marca15B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marca8B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(siguiente7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguiente7B)
                    .addComponent(anterior7B))
                .addGap(40, 40, 40))
        );

        Carga.add(siguiente7, "card8");

        siguiente8.setBackground(new java.awt.Color(0, 0, 0));
        siguiente8.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Indique Capacidad de la Placa de Video en MB:");

        buttonGroup6.add(capacidadPlaca1B);
        capacidadPlaca1B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadPlaca1B.setText("2048MB");

        buttonGroup6.add(capacidadPlaca2B);
        capacidadPlaca2B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadPlaca2B.setText("4096MB");

        buttonGroup6.add(capacidadPlaca3B);
        capacidadPlaca3B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadPlaca3B.setText("6144MB");

        buttonGroup6.add(capacidadPlaca4B);
        capacidadPlaca4B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadPlaca4B.setText("8192MB");

        buttonGroup6.add(capacidadPlaca5B);
        capacidadPlaca5B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadPlaca5B.setText("12288MB");

        buttonGroup6.add(capacidadPlaca6B);
        capacidadPlaca6B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadPlaca6B.setText("24576MB");

        siguiente8B.setBackground(new java.awt.Color(0, 0, 0));
        siguiente8B.setForeground(new java.awt.Color(255, 255, 255));
        siguiente8B.setText("Siguiente");
        siguiente8B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente8BActionPerformed(evt);
            }
        });

        anterior8B.setBackground(new java.awt.Color(0, 0, 0));
        anterior8B.setForeground(new java.awt.Color(255, 255, 255));
        anterior8B.setText("Anterior");
        anterior8B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anterior8BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente8Layout = new javax.swing.GroupLayout(siguiente8);
        siguiente8.setLayout(siguiente8Layout);
        siguiente8Layout.setHorizontalGroup(
            siguiente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(siguiente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(capacidadPlaca1B)
                    .addComponent(capacidadPlaca2B)
                    .addComponent(capacidadPlaca3B)
                    .addComponent(capacidadPlaca4B)
                    .addGroup(siguiente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(capacidadPlaca6B)
                        .addComponent(capacidadPlaca5B)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente8Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente8Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(anterior8B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siguiente8B)
                .addGap(34, 34, 34))
        );
        siguiente8Layout.setVerticalGroup(
            siguiente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(capacidadPlaca1B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(capacidadPlaca2B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(capacidadPlaca3B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(capacidadPlaca4B)
                .addGap(12, 12, 12)
                .addComponent(capacidadPlaca5B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(capacidadPlaca6B)
                .addGap(18, 18, 18)
                .addGroup(siguiente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguiente8B)
                    .addComponent(anterior8B))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        Carga.add(siguiente8, "card9");

        siguiente9N.setBackground(new java.awt.Color(0, 0, 0));
        siguiente9N.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Indique Capacidad de la Bateria:");

        capacidadBateria1B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup7.add(capacidadBateria1B);
        capacidadBateria1B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadBateria1B.setText("4400mAh");

        capacidadBateria2B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup7.add(capacidadBateria2B);
        capacidadBateria2B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadBateria2B.setText("5200mAh");

        capacidadBateria3B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup7.add(capacidadBateria3B);
        capacidadBateria3B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadBateria3B.setText("5600mAh");

        capacidadBateria4B.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup7.add(capacidadBateria4B);
        capacidadBateria4B.setForeground(new java.awt.Color(255, 255, 255));
        capacidadBateria4B.setText("5800mAh");

        siguiente9NB.setBackground(new java.awt.Color(0, 0, 0));
        siguiente9NB.setForeground(new java.awt.Color(255, 255, 255));
        siguiente9NB.setText("Siguiente");
        siguiente9NB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente9NBActionPerformed(evt);
            }
        });

        anterior9NB.setBackground(new java.awt.Color(0, 0, 0));
        anterior9NB.setForeground(new java.awt.Color(255, 255, 255));
        anterior9NB.setText("Anterior");
        anterior9NB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anterior9NBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente9NLayout = new javax.swing.GroupLayout(siguiente9N);
        siguiente9N.setLayout(siguiente9NLayout);
        siguiente9NLayout.setHorizontalGroup(
            siguiente9NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente9NLayout.createSequentialGroup()
                .addGroup(siguiente9NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siguiente9NLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel11))
                    .addGroup(siguiente9NLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(capacidadBateria1B))
                    .addGroup(siguiente9NLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(capacidadBateria2B))
                    .addGroup(siguiente9NLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(capacidadBateria3B))
                    .addGroup(siguiente9NLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(capacidadBateria4B)))
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(siguiente9NLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(anterior9NB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siguiente9NB)
                .addGap(37, 37, 37))
        );
        siguiente9NLayout.setVerticalGroup(
            siguiente9NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente9NLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(capacidadBateria1B)
                .addGap(18, 18, 18)
                .addComponent(capacidadBateria2B)
                .addGap(18, 18, 18)
                .addComponent(capacidadBateria3B)
                .addGap(18, 18, 18)
                .addComponent(capacidadBateria4B)
                .addGap(59, 59, 59)
                .addGroup(siguiente9NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anterior9NB)
                    .addComponent(siguiente9NB))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        Carga.add(siguiente9N, "card10");

        siguiente10N.setBackground(new java.awt.Color(0, 0, 0));
        siguiente10N.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ingrese Peso en Kg.:");

        pesoB.setMaximum(3000);
        pesoB.setMinimum(600);
        pesoB.setMinorTickSpacing(100);
        pesoB.setPaintLabels(true);
        pesoB.setPaintTicks(true);
        pesoB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pesoBStateChanged(evt);
            }
        });

        pesoL.setForeground(new java.awt.Color(255, 255, 255));

        cargarNB.setBackground(new java.awt.Color(0, 0, 0));
        cargarNB.setForeground(new java.awt.Color(255, 255, 255));
        cargarNB.setText("Cargar");
        cargarNB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarNBActionPerformed(evt);
            }
        });

        anterior10NB.setBackground(new java.awt.Color(0, 0, 0));
        anterior10NB.setForeground(new java.awt.Color(255, 255, 255));
        anterior10NB.setText("Anterior");
        anterior10NB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anterior10NBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente10NLayout = new javax.swing.GroupLayout(siguiente10N);
        siguiente10N.setLayout(siguiente10NLayout);
        siguiente10NLayout.setHorizontalGroup(
            siguiente10NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente10NLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(pesoL)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente10NLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(siguiente10NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente10NLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente10NLayout.createSequentialGroup()
                        .addComponent(pesoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente10NLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(anterior10NB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cargarNB)
                .addGap(37, 37, 37))
        );
        siguiente10NLayout.setVerticalGroup(
            siguiente10NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente10NLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel12)
                .addGap(43, 43, 43)
                .addComponent(pesoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(pesoL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(siguiente10NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargarNB)
                    .addComponent(anterior10NB))
                .addGap(48, 48, 48))
        );

        Carga.add(siguiente10N, "card11");

        siguiente9A.setBackground(new java.awt.Color(0, 0, 0));
        siguiente9A.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Indique si su Perifericos Soportan Bluetooth:");

        buttonGroup8.add(perifericos1B);
        perifericos1B.setForeground(new java.awt.Color(255, 255, 255));
        perifericos1B.setText("SI");

        buttonGroup8.add(perifericos2B);
        perifericos2B.setForeground(new java.awt.Color(255, 255, 255));
        perifericos2B.setSelected(true);
        perifericos2B.setText("NO");

        cargarAB.setBackground(new java.awt.Color(0, 0, 0));
        cargarAB.setForeground(new java.awt.Color(255, 255, 255));
        cargarAB.setText("Cargar");
        cargarAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarABActionPerformed(evt);
            }
        });

        anterior9AB.setBackground(new java.awt.Color(0, 0, 0));
        anterior9AB.setForeground(new java.awt.Color(255, 255, 255));
        anterior9AB.setText("Anterior");
        anterior9AB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anterior9ABActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siguiente9ALayout = new javax.swing.GroupLayout(siguiente9A);
        siguiente9A.setLayout(siguiente9ALayout);
        siguiente9ALayout.setHorizontalGroup(
            siguiente9ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siguiente9ALayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(anterior9AB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cargarAB)
                .addGap(33, 33, 33))
            .addGroup(siguiente9ALayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel13)
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(siguiente9ALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(perifericos1B)
                .addGap(87, 87, 87)
                .addComponent(perifericos2B)
                .addGap(123, 123, 123))
        );
        siguiente9ALayout.setVerticalGroup(
            siguiente9ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siguiente9ALayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel13)
                .addGap(52, 52, 52)
                .addGroup(siguiente9ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perifericos1B)
                    .addComponent(perifericos2B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(siguiente9ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargarAB)
                    .addComponent(anterior9AB))
                .addGap(39, 39, 39))
        );

        Carga.add(siguiente9A, "card12");

        Contenedor.add(Carga, "card3");
        Carga.getAccessibleContext().setAccessibleParent(Carga);

        Muestra.setBackground(new java.awt.Color(0, 0, 0));

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));

        muestraText.setBackground(new java.awt.Color(0, 0, 0));
        muestraText.setColumns(20);
        muestraText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        muestraText.setForeground(new java.awt.Color(255, 255, 255));
        muestraText.setRows(5);
        jScrollPane2.setViewportView(muestraText);

        siguienteM.setBackground(new java.awt.Color(0, 0, 0));
        siguienteM.setForeground(new java.awt.Color(255, 255, 255));
        siguienteM.setText("Siguiente");
        siguienteM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteMActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("INVENTARIO:");

        anteriorM.setBackground(new java.awt.Color(0, 0, 0));
        anteriorM.setForeground(new java.awt.Color(255, 255, 255));
        anteriorM.setText("Anterior");
        anteriorM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorMActionPerformed(evt);
            }
        });

        terminarM.setBackground(new java.awt.Color(0, 0, 0));
        terminarM.setForeground(new java.awt.Color(255, 255, 255));
        terminarM.setText("Terminar");
        terminarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MuestraLayout = new javax.swing.GroupLayout(Muestra);
        Muestra.setLayout(MuestraLayout);
        MuestraLayout.setHorizontalGroup(
            MuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MuestraLayout.createSequentialGroup()
                .addGroup(MuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MuestraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(MuestraLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(anteriorM)
                        .addGap(54, 54, 54)
                        .addComponent(terminarM)
                        .addGap(52, 52, 52)
                        .addComponent(siguienteM)
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(MuestraLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MuestraLayout.setVerticalGroup(
            MuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MuestraLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(MuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguienteM)
                    .addComponent(anteriorM)
                    .addComponent(terminarM))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        Contenedor.add(Muestra, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguiente5BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente5BActionPerformed
        // TODO add your handling code here:
        if(disco1B.isSelected()){
            capacidadDiscoGB = 160;
        }
        if(disco2B.isSelected()){
            capacidadDiscoGB = 250;
        }
        if(disco3B.isSelected()){
            capacidadDiscoGB = 320;
        }
        if(disco4B.isSelected()){
            capacidadDiscoGB = 500;
        }
        if(disco5B.isSelected()){
            capacidadDiscoGB = 1000;
        }
        if(disco6B.isSelected()){
            capacidadDiscoGB = 1500;
        }
        if(disco7B.isSelected()){
            capacidadDiscoGB = 2000;
        }
        if(disco8B.isSelected()){
            capacidadDiscoGB = 2500;
        }
        if(disco9B.isSelected()){
            capacidadDiscoGB = 3000;
        }

        if(capacidadDiscoGB!=0){
            Contenedor.removeAll();
            Contenedor.add(siguiente6);
            Contenedor.repaint();
            Contenedor.revalidate();
        }
    }//GEN-LAST:event_siguiente5BActionPerformed

    private void anterior5BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anterior5BActionPerformed
        // TODO add your handling code here:
        Contenedor.removeAll();
        Contenedor.add(siguiente4);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_anterior5BActionPerformed

    private void siguiente1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente1BActionPerformed
        // TODO add your handling code here:
        if(tipo1B.isSelected()){
            tipo = tipo1B.getText();
        }
        if(tipo2B.isSelected()){
            tipo = tipo2B.getText();
        }
        if(tipo!=null){
            Contenedor.removeAll();
            Contenedor.add(siguiente2);
            Contenedor.repaint();
            Contenedor.revalidate();
        }
    }//GEN-LAST:event_siguiente1BActionPerformed

    private void RAM2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAM2BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RAM2BActionPerformed

    private void siguiente4BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente4BActionPerformed
        // TODO add your handling code here:
        if(RAM1B.isSelected()){
            capacidadMemoria = 4;
        }
        if(RAM2B.isSelected()){
            capacidadMemoria = 8;
        }
        if(RAM3B.isSelected()){
            capacidadMemoria = 16;
        }
        if(RAM4B.isSelected()){
            capacidadMemoria = 32;
        }
        if(RAM5B.isSelected()){
            capacidadMemoria = 64;
        }
        if(capacidadMemoria != 0){
            Contenedor.removeAll();
            Contenedor.add(siguiente5);
            Contenedor.repaint();
            Contenedor.revalidate();
        }
    }//GEN-LAST:event_siguiente4BActionPerformed

    private void anterior4BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anterior4BActionPerformed
        // TODO add your handling code here:
        Contenedor.removeAll();
        Contenedor.add(siguiente3);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_anterior4BActionPerformed

    private void velocidadBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_velocidadBStateChanged
        // TODO add your handling code here:
        valorL.setText(((float)velocidadB.getValue()/1000)+"GHz.");
    }//GEN-LAST:event_velocidadBStateChanged

    private void siguiente3BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente3BActionPerformed
        // TODO add your handling code here:
        velocidadProcesador = (float)velocidadB.getValue()/1000;
        if(velocidadProcesador!=0){
            Contenedor.removeAll();
            Contenedor.add(siguiente4);
            Contenedor.repaint();
            Contenedor.revalidate();
        }
    }//GEN-LAST:event_siguiente3BActionPerformed

    private void anterior3BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anterior3BActionPerformed
        // TODO add your handling code here:
        Contenedor.removeAll();
        Contenedor.add(siguiente2);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_anterior3BActionPerformed

    private void siguiente2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente2BActionPerformed
        // TODO add your handling code here:
        if(marcaProcesador1B.isSelected()){
            marcaProcesador = marcaProcesador1B.getText();
        }
        if(marcaProcesador2B.isSelected()){
            marcaProcesador = marcaProcesador2B.getText();
        }
        if(marcaProcesador!=null){
            Contenedor.removeAll();
            Contenedor.add(siguiente3);
            Contenedor.repaint();
            Contenedor.revalidate();
        }
    }//GEN-LAST:event_siguiente2BActionPerformed

    private void anterior2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anterior2BActionPerformed
        // TODO add your handling code here:
        Contenedor.removeAll();
        Contenedor.add(siguiente1);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_anterior2BActionPerformed

    private void rpmBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rpmBStateChanged
        // TODO add your handling code here:
        valor2L.setText(rpmB.getValue()+"rpm.");
    }//GEN-LAST:event_rpmBStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        rpm = rpmB.getValue();
        Contenedor.removeAll();
        Contenedor.add(siguiente7);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void anterior6BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anterior6BActionPerformed
        // TODO add your handling code here:
        Contenedor.removeAll();
        Contenedor.add(siguiente5);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_anterior6BActionPerformed

    private void siguiente7BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente7BActionPerformed
        // TODO add your handling code here:
        if(marca1B.isSelected()){
            marcaPlacaVideo = marca1B.getText();
        }
        if(marca2B.isSelected()){
            marcaPlacaVideo = marca2B.getText();
        }
        if(marca3B.isSelected()){
            marcaPlacaVideo = marca3B.getText();
        }
        if(marca4B.isSelected()){
            marcaPlacaVideo = marca4B.getText();
        }
        if(marca5B.isSelected()){
            marcaPlacaVideo = marca5B.getText();
        }
        if(marca6B.isSelected()){
            marcaPlacaVideo = marca6B.getText();
        }
        if(marca7B.isSelected()){
            marcaPlacaVideo = marca7B.getText();
        }
        if(marca8B.isSelected()){
            marcaPlacaVideo = marca8B.getText();
        }
        if(marca9B.isSelected()){
            marcaPlacaVideo = marca9B.getText();
        }
        if(marca10B.isSelected()){
            marcaPlacaVideo = marca10B.getText();
        }
        if(marca11B.isSelected()){
            marcaPlacaVideo = marca11B.getText();
        }
        if(marca12B.isSelected()){
            marcaPlacaVideo = marca12B.getText();
        }
        if(marca13B.isSelected()){
            marcaPlacaVideo = marca13B.getText();
        }
        if(marca14B.isSelected()){
            marcaPlacaVideo = marca14B.getText();
        }
        if(marca15B.isSelected()){
            marcaPlacaVideo = marca15B.getText();
        }
        if(marcaPlacaVideo!=null){
            Contenedor.removeAll();
            Contenedor.add(siguiente8);
            Contenedor.repaint();
            Contenedor.revalidate();
        }
    }//GEN-LAST:event_siguiente7BActionPerformed

    private void anterior7BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anterior7BActionPerformed
        // TODO add your handling code here:
        Contenedor.removeAll();
        Contenedor.add(siguiente6);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_anterior7BActionPerformed

    private void siguiente8BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente8BActionPerformed
        // TODO add your handling code here:
        if(capacidadPlaca1B.isSelected()){
            capacidadPlacaVideoMB = 2048;
        }
        if(capacidadPlaca2B.isSelected()){
            capacidadPlacaVideoMB = 4096;
        }
        if(capacidadPlaca3B.isSelected()){
            capacidadPlacaVideoMB = 6144;
        }
        if(capacidadPlaca4B.isSelected()){
            capacidadPlacaVideoMB = 8192;
        }
        if(capacidadPlaca5B.isSelected()){
            capacidadPlacaVideoMB = 12288;
        }
        if(capacidadPlaca6B.isSelected()){
            capacidadPlacaVideoMB = 24576;
        }
        if(capacidadPlacaVideoMB != 0){
            if(tipo.equals("Notebook")){
                Contenedor.removeAll();
                Contenedor.add(siguiente9N);
                Contenedor.repaint();
                Contenedor.revalidate();
            }else{
                Contenedor.removeAll();
                Contenedor.add(siguiente9A);
                Contenedor.repaint();
                Contenedor.revalidate();
            }
        }
    }//GEN-LAST:event_siguiente8BActionPerformed

    private void anterior8BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anterior8BActionPerformed
        // TODO add your handling code here:
        Contenedor.removeAll();
        Contenedor.add(siguiente7);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_anterior8BActionPerformed

    private void siguiente9NBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente9NBActionPerformed
        // TODO add your handling code here:
        if(capacidadBateria1B.isSelected()){
            capacidadBateria = 4400;
        }
        if(capacidadBateria2B.isSelected()){
            capacidadBateria = 5200;
        }
        if(capacidadBateria3B.isSelected()){
            capacidadBateria = 5600;
        }
        if(capacidadBateria4B.isSelected()){
            capacidadBateria = 5800;
        }
        if(capacidadBateria!=0){
            Contenedor.removeAll();
            Contenedor.add(siguiente10N);
            Contenedor.repaint();
            Contenedor.revalidate();
        }
    }//GEN-LAST:event_siguiente9NBActionPerformed

    private void anterior9NBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anterior9NBActionPerformed
        // TODO add your handling code here:
        Contenedor.removeAll();
        Contenedor.add(siguiente8);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_anterior9NBActionPerformed

    private void pesoBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pesoBStateChanged
        // TODO add your handling code here:
        pesoL.setText(((float)pesoB.getValue()/1000)+"Kg.");
    }//GEN-LAST:event_pesoBStateChanged

    private void cargarNBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarNBActionPerformed
        // TODO add your handling code here:
        Inicio inicio = new Inicio();
        peso = (float)pesoB.getValue()/1000;
        
        inventario.agregarComputadora(new Notebook(capacidadBateria, peso, marcaProcesador, velocidadProcesador, capacidadMemoria, capacidadDiscoGB, rpm, marcaPlacaVideo, capacidadPlacaVideoMB));
        
        Contenedor.removeAll();
        Contenedor.add(inicio);
        Contenedor.repaint();
        Contenedor.revalidate();

    }//GEN-LAST:event_cargarNBActionPerformed

    private void anterior10NBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anterior10NBActionPerformed
        // TODO add your handling code here:
        Contenedor.removeAll();
        Contenedor.add(siguiente9N);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_anterior10NBActionPerformed

    private void cargarABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarABActionPerformed
        // TODO add your handling code here:
        Inicio inicio = new Inicio();
        if(perifericos1B.isSelected()){
            perifericosBluetooth=true;
        }else{
            perifericosBluetooth=false;
        }

        
        inventario.agregarComputadora(new All_In_One(perifericosBluetooth, marcaProcesador, velocidadProcesador,  capacidadMemoria,  capacidadDiscoGB, rpm,  marcaPlacaVideo, capacidadPlacaVideoMB));
        
        Contenedor.removeAll();
        Contenedor.add(inicio);
        Contenedor.repaint();
        Contenedor.revalidate();

    }//GEN-LAST:event_cargarABActionPerformed

    private void anterior9ABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anterior9ABActionPerformed
        // TODO add your handling code here:
        Contenedor.removeAll();
        Contenedor.add(siguiente8);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_anterior9ABActionPerformed

    private void inicioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioBActionPerformed
        // TODO add your handling code here:
        Inicio inicio = new Inicio();
        Contenedor.removeAll();
        Contenedor.add(inicio );
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_inicioBActionPerformed

    private void cargarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarBActionPerformed
        // TODO add your handling code here:

        Contenedor.removeAll();
        Contenedor.add(siguiente1);
        Contenedor.repaint();
        Contenedor.revalidate();

    }//GEN-LAST:event_cargarBActionPerformed

    private void siguienteMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteMActionPerformed
        // TODO add your handling code here:
        Inicio inicio = new Inicio();
        if(it.hasNext()){
            Computadora comp = it.next();
            muestraText.setText(comp.toString());
        }else{
           
        }
    }//GEN-LAST:event_siguienteMActionPerformed

    private void mostrarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarBActionPerformed
        // TODO add your handling code here:
        Inicio inicio = new Inicio();
        it = inventario.getNegocio().listIterator();
        if(it.hasNext()){
            Computadora comp = it.next();
            muestraText.setText(comp.toString());
            Contenedor.removeAll();
            Contenedor.add(Muestra);
            Contenedor.repaint();
            Contenedor.revalidate();
        }else{
            Contenedor.removeAll();
            Contenedor.add(inicio);
            Contenedor.repaint();
            Contenedor.revalidate();
            it = inventario.getNegocio().listIterator();
            muestraText.setText("");
        }
        
        
    }//GEN-LAST:event_mostrarBActionPerformed

    private void anteriorMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorMActionPerformed
        // TODO add your handling code here:
        Inicio inicio = new Inicio();
        if(it.hasPrevious()){
            Computadora comp = it.previous();
            muestraText.setText(comp.toString());
        }else{
            
        }
    }//GEN-LAST:event_anteriorMActionPerformed

    private void terminarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarMActionPerformed
        // TODO add your handling code here:
        Inicio inicio = new Inicio();
            Contenedor.removeAll();
            Contenedor.add(inicio);
            Contenedor.repaint();
            Contenedor.revalidate();
            it = inventario.getNegocio().listIterator();
            muestraText.setText("");
    }//GEN-LAST:event_terminarMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Carga;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JPanel Inicio;
    private javax.swing.JPanel Muestra;
    private javax.swing.JRadioButton RAM1B;
    private javax.swing.JRadioButton RAM2B;
    private javax.swing.JRadioButton RAM3B;
    private javax.swing.JRadioButton RAM4B;
    private javax.swing.JRadioButton RAM5B;
    private javax.swing.JButton anterior10NB;
    private javax.swing.JButton anterior2B;
    private javax.swing.JButton anterior3B;
    private javax.swing.JButton anterior4B;
    private javax.swing.JButton anterior5B;
    private javax.swing.JButton anterior6B;
    private javax.swing.JButton anterior7B;
    private javax.swing.JButton anterior8B;
    private javax.swing.JButton anterior9AB;
    private javax.swing.JButton anterior9NB;
    private javax.swing.JButton anteriorM;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JRadioButton capacidadBateria1B;
    private javax.swing.JRadioButton capacidadBateria2B;
    private javax.swing.JRadioButton capacidadBateria3B;
    private javax.swing.JRadioButton capacidadBateria4B;
    private javax.swing.JRadioButton capacidadPlaca1B;
    private javax.swing.JRadioButton capacidadPlaca2B;
    private javax.swing.JRadioButton capacidadPlaca3B;
    private javax.swing.JRadioButton capacidadPlaca4B;
    private javax.swing.JRadioButton capacidadPlaca5B;
    private javax.swing.JRadioButton capacidadPlaca6B;
    private javax.swing.JButton cargarAB;
    private javax.swing.JButton cargarB;
    private javax.swing.JButton cargarNB;
    private javax.swing.JRadioButton disco1B;
    private javax.swing.JRadioButton disco2B;
    private javax.swing.JRadioButton disco3B;
    private javax.swing.JRadioButton disco4B;
    private javax.swing.JRadioButton disco5B;
    private javax.swing.JRadioButton disco6B;
    private javax.swing.JRadioButton disco7B;
    private javax.swing.JRadioButton disco8B;
    private javax.swing.JRadioButton disco9B;
    private javax.swing.JButton inicioB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton marca10B;
    private javax.swing.JRadioButton marca11B;
    private javax.swing.JRadioButton marca12B;
    private javax.swing.JRadioButton marca13B;
    private javax.swing.JRadioButton marca14B;
    private javax.swing.JRadioButton marca15B;
    private javax.swing.JRadioButton marca1B;
    private javax.swing.JRadioButton marca2B;
    private javax.swing.JRadioButton marca3B;
    private javax.swing.JRadioButton marca4B;
    private javax.swing.JRadioButton marca5B;
    private javax.swing.JRadioButton marca6B;
    private javax.swing.JRadioButton marca7B;
    private javax.swing.JRadioButton marca8B;
    private javax.swing.JRadioButton marca9B;
    private javax.swing.JRadioButton marcaProcesador1B;
    private javax.swing.JRadioButton marcaProcesador2B;
    private javax.swing.JButton mostrarB;
    private javax.swing.JTextArea muestraText;
    private javax.swing.JRadioButton perifericos1B;
    private javax.swing.JRadioButton perifericos2B;
    private javax.swing.JSlider pesoB;
    private javax.swing.JLabel pesoL;
    private javax.swing.JSlider rpmB;
    private javax.swing.JPanel siguiente1;
    private javax.swing.JPanel siguiente10N;
    private javax.swing.JButton siguiente1B;
    private javax.swing.JPanel siguiente2;
    private javax.swing.JButton siguiente2B;
    private javax.swing.JPanel siguiente3;
    private javax.swing.JButton siguiente3B;
    private javax.swing.JPanel siguiente4;
    private javax.swing.JButton siguiente4B;
    private javax.swing.JPanel siguiente5;
    private javax.swing.JButton siguiente5B;
    private javax.swing.JPanel siguiente6;
    private javax.swing.JPanel siguiente7;
    private javax.swing.JButton siguiente7B;
    private javax.swing.JPanel siguiente8;
    private javax.swing.JButton siguiente8B;
    private javax.swing.JPanel siguiente9A;
    private javax.swing.JPanel siguiente9N;
    private javax.swing.JButton siguiente9NB;
    private javax.swing.JButton siguienteM;
    private javax.swing.JButton terminarM;
    private javax.swing.JRadioButton tipo1B;
    private javax.swing.JRadioButton tipo2B;
    private javax.swing.JLabel valor2L;
    private javax.swing.JLabel valorL;
    private javax.swing.JSlider velocidadB;
    // End of variables declaration//GEN-END:variables
}
